$env:DB_URL="jdbc:mysql://127.0.0.1:3306/scoring_mvp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true"
$env:DB_USERNAME="scoring_app"
$env:DB_PASSWORD="your_mysql_password"
$env:JWT_SECRET="<replace-with-your-own-random-secret-at-least-32-chars>"
$env:WECHAT_APP_ID="wx8113b05d52ef52b3"
$env:WECHAT_APP_SECRET="your_wechat_app_secret"
